### ISSUE TITLE
Unclear example chapter-02/08-definitions/macro.cmake

### ISSUE THREAD

**Issue by okellogg** [PacktPublishing/Modern-CMake-for-Cpp-2E#5]
In the example, the line
`Test("called value")`
does not make sense to me:
The string "called value" is passed to the macro argument `myVar` and in the macro, I'm not sure what this would do,
`set(myVar "new value")`

Here is my proposed changed example (omitting first line `cmake_minimum_required`):
```
macro(Test arg)
  set(${arg} "new value")
  message("argument: ${arg}")
endmacro()

set(myVar "first value")
message("myVar is now: ${myVar}")
Test(myVar)
message("myVar is now: ${myVar}")
```

Running this with `cmake -P macro.cmake` produces the output:
```
myVar is now: first value
argument: myVar
myVar is now: new value
```

**Comment by Drakemor** [comment]
I see where you're coming from. Let me clarify furhter. Please look at the original example:
```
# ch02/08-definitions/macro.cmake
macro(MyMacro myVar)
  set(myVar "new value")
  message("argument: ${myVar}")
endmacro()
```
What we know about macros is that they don't create a local scope. This means that `set()` call will affect the variables in the scope of the caller. So when we print the variable `myVar` before and after calling the macro, we can see it was changed.

However, something strange happens as well: printing the argument passed to the macro, within the macro, after the variable was changed - produces "called value". This is a possible issue, when writing macros, because we would normally expect the `myVar` within the scope of macro to already be set to "new value" as it has changed the calling scope; but this is not the case.

The book touches on this a bit more in depth, I hope this clarification helps.

**Comment by okellogg** [comment]
Thanks for clarifying.
That's certainly an interesting aspect of the weirdness of macros
(I was thinking more about a typical usage pattern).
